package org.ymxr;

import java.io.ByteArrayOutputStream;
import java.nio.charset.StandardCharsets;

/**
 * A YM6! dump written from register vectors, for the tunes built rather
 * than recorded. Carried from YMX's {@code org.ymx.rig.GenYm}, the part of
 * it that writes a file: the two built dumps under {@code ym/test} are
 * byte for byte what YMX's builder writes, and this keeps them so here.
 */
final class GenYm {

    /** R13's value where a frame leaves the envelope running. */
    static final int NO_ENVELOPE_CHANGE = 0xFF;

    private GenYm() {
    }

    /** A complete YM6! file, interleaved, at 50 Hz, repeating at frame 0:
     *  {@code source[r][frame]} for R0 to R15, and the drums as 8-bit
     *  samples, stored as a YM6 file stores them. */
    static byte[] ym6File(int frames, byte[][] source, byte[]... drums) {
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        out.writeBytes("YM6!LeOnArD!".getBytes(StandardCharsets.US_ASCII));
        writeLong(out, frames);
        writeLong(out, 1);                          // interleaved
        writeWord(out, drums.length);               // digidrums
        writeLong(out, 2000000);                    // master clock
        writeWord(out, 50);                         // player rate
        writeLong(out, 0);                          // loop frame
        writeWord(out, 0);                          // additional data size
        for (byte[] drum : drums) {
            writeLong(out, drum.length);
            out.writeBytes(drum);
        }
        out.writeBytes("Synthetic\0Test\0Generated by the rig\0"
                .getBytes(StandardCharsets.US_ASCII));
        for (byte[] vector : source) {
            out.write(vector, 0, frames);
        }
        out.writeBytes("End!".getBytes(StandardCharsets.US_ASCII));
        return out.toByteArray();
    }

    private static void writeWord(ByteArrayOutputStream out, int value) {
        out.write(value >>> 8);
        out.write(value);
    }

    private static void writeLong(ByteArrayOutputStream out, int value) {
        writeWord(out, value >>> 16);
        writeWord(out, value);
    }
}
